---
- name: install lightdm
  apt:
    pkg: "{{ item }}"
  with_items:
  - lightdm-gtk-greeter
  - lightdm
  - policykit-1
  - x11-xserver-utils

- name: create dir for configs
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory

- name: configure lightdm autologin
  template:
    src: templates/autologin.conf.j2
    dest: /etc/lightdm/lightdm.conf.d/autologin.conf
  when: autologin
  notify: restart lightdm

- name: kill pulseaudio with fire on logout
  copy:
    src: files/kill-pulseaudio.conf
    dest: /etc/lightdm/lightdm.conf.d/kill-pulseaudio.conf
  notify: restart lightdm
