---
- name: install a web server to host late_command.sh
  apt:
    name: "{{ item }}"
  with_items:
  - nginx

- name: download TFTP boot image
  get_url:
    url: "{{ netboot_image }}"
    dest: /srv/tftp/netboot.tar.gz

- name: extract TFTP boot image
  unarchive:
    src: /srv/tftp/netboot.tar.gz
    dest: /srv/tftp
    remote_src: true
    creates: /srv/tftp/pxelinux.0

- name: create dir for configs
  file:
    path: "{{ web_root }}/{{ item }}"
    state: directory
    recurse: true
    # owner:  "{{ user_name }}"
    # group:  "{{ user_name }}"
  with_items:
  - lc
  - d-i/xenial
  - d-i/jessie

- name: write xenial/preseed.cfg
  template:
    src: preseed.cfg.j2
    dest: "{{ web_root }}/d-i/xenial/preseed.cfg"

- name: write jessie/preseed.cfg
  template:
    src: preseed.cfg.j2
    dest: "{{ web_root }}/d-i/jessie/preseed.cfg"

- name: push late_command.sh
  copy:
    src: files/late_command.sh
    dest: "{{ web_root }}/lc/late_command.sh"

- name: inject preseed into menu (find files)
  find:
    paths: /srv/tftp
    recurse: true
    patterns: txt.cfg
  register: menus

- name: inject preseed into menu (do injection)
  lineinfile:
    dest: "{{ item.path }}"
    regexp: (\s+append vga=.*\s+initrd=\S+)\s+(?!auto=true)(.*)
    backrefs: true
    line: \1 auto=true interface=auto url={{ inventory_hostname }} DEBCONF_DEBUG=5 partman-auto/disk="/dev/hda" \2

  with_items: "{{ menus.files }}"
